version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: surveillance_db
    environment:
      POSTGRES_USER: surveillance_user
      POSTGRES_PASSWORD: surveillance_pass
      POSTGRES_DB: surveillance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  postgres_data: